import type { Metadata } from "next";
import "./globals.css";
import "../styles/reset.css";
import Header from "../components/header";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* 공통 Header */}
        <Header />

        {/* 메인 컨텐츠 */}
        <main>{children}</main>

        {/* 공통 Footer */}
        <Footer />
      </body>
    </html>
  );
}
