import type { Metadata } from "next";
import "./globals.css";
import "../styles/reset.css";

import SearchBar from "@/components/SearchBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-6 shadow-md">
          <SearchBar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
